version: "3.8"

services:
  cinetech:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_TMDB_API_KEY: ${VITE_TMDB_API_KEY}
        VITE_TMDB_BASE_URL: ${VITE_TMDB_BASE_URL:-https://api.themoviedb.org/3}
    container_name: cinetech
    restart: unless-stopped
    ports:
      - "127.0.0.1:3003:80"
    networks:
      - web

networks:
  web:
    external: true
